import type {
  BureauAddress,
  ClientProfile,
  LetterTemplate,
} from "./types";

const seededAt = "2026-06-01T12:00:00.000Z";

export const demoClient: ClientProfile = {
  id: "demo-contact",
  firstName: "Jordan",
  lastName: "Williams",
  address: "1842 Magnolia Avenue",
  city: "Atlanta",
  state: "GA",
  zip: "30318",
  phone: "(404) 555-0148",
  email: "jordan.williams@example.com",
};

export const bureauAddresses: BureauAddress[] = [
  ["Experian", "Regular Dispute Address", "P.O. Box 4500", "", "Allen", "TX", "75013"],
  ["Experian", "Legal Department", "P.O. Box 4500", "Attn: Legal Department", "Allen", "TX", "75013"],
  ["Experian", "Fraud Department", "P.O. Box 9554", "", "Allen", "TX", "75013"],
  ["TransUnion", "Regular Dispute Address", "P.O. Box 2000", "", "Chester", "PA", "19016-2000"],
  ["TransUnion", "Legal Department", "P.O. Box 2000", "Attn: Legal Department", "Chester", "PA", "19016-2000"],
  ["TransUnion", "Fraud Department", "P.O. Box 2000", "Attn: Fraud Victim Assistance", "Chester", "PA", "19016-2000"],
  ["Equifax", "Regular Dispute Address", "P.O. Box 740256", "", "Atlanta", "GA", "30374-0256"],
  ["Equifax", "Legal Department", "P.O. Box 740256", "Attn: Legal Department", "Atlanta", "GA", "30374-0256"],
  ["Equifax", "Fraud Department", "P.O. Box 740256", "Attn: Fraud Department", "Atlanta", "GA", "30374-0256"],
  ["Innovis", "Consumer Assistance", "P.O. Box 26", "Consumer Assistance", "Pittsburgh", "PA", "15230-0026"],
  ["Equifax","Information Services LLC","P.O. Box 740256","Consumer Dispute Department","Atlanta","GA","30374-0256"],
["Experian","Consumer Information Services","P.O. Box 4500","Dispute Department","Allen","TX","75013"],
["TransUnion","Consumer Solutions","P.O. Box 2000","Consumer Dispute Center","Chester","PA","19016-2000"],
["Innovis","Consumer Assistance","P.O. Box 26","Consumer Assistance","Pittsburgh","PA","15230-0026"],
["LexisNexis Risk Solutions","Consumer Center","P.O. Box 105108","Consumer Disclosure Center","Atlanta","GA","30348-5108"],
["CoreLogic Credco","Consumer Relations","P.O. Box 509124","Consumer Relations","San Diego","CA","92150"],
["CoreLogic Teletrack","Consumer Assistance","P.O. Box 509124","Consumer Relations","San Diego","CA","92150"],
["ChexSystems","Consumer Relations","P.O. Box 583399","Consumer Relations","Minneapolis","MN","55458"],
["Early Warning Services","Consumer Services","16552 North 90th Street","Consumer Services","Scottsdale","AZ","85260"],
["The Work Number","Consumer Service Center","P.O. Box 105281","Consumer Service Center","Atlanta","GA","30348"],
["MicroBilt","Consumer Relations","1640 Airport Road","Consumer Relations","Kennesaw","GA","30144"],
["DataX Ltd.","Consumer Assistance","P.O. Box 740249","Consumer Assistance","Atlanta","GA","30374"],
["SageStream LLC","Consumer Assistance","P.O. Box 503793","Consumer Assistance","San Diego","CA","92150"],
["FactorTrust","Consumer Relations","P.O. Box 3653","Consumer Relations","Alpharetta","GA","30023"],
["NCTUE","Consumer Assistance","P.O. Box 105161","Consumer Assistance","Atlanta","GA","30348"],
["Clarity Services","Consumer Relations","P.O. Box 5717","Consumer Relations","Clearwater","FL","33758"],
["Certegy Check Services","Consumer Response Center","P.O. Box 30046","Consumer Response Center","Tampa","FL","33630"],
["TeleCheck Services","Consumer Resolution","P.O. Box 4514","Consumer Resolution","Houston","TX","77210"],
["L2C Inc.","Consumer Assistance","P.O. Box 550598","Consumer Assistance","Jacksonville","FL","32255"],
["Medical Information Bureau (MIB)","Consumer Services","50 Braintree Hill Park","Consumer Services","Braintree","MA","02184"],
  ["Capital One","Office of the President","P.O. Box 30285","Executive Customer Relations","Salt Lake City","UT","84130-0285"],
["JPMorgan Chase","Executive Office","P.O. Box 15298","Executive Office","Wilmington","DE","19850-5298"],
["Bank of America","Executive Customer Relations","P.O. Box 25118","Executive Customer Relations","Tampa","FL","33622-5118"],
["Citibank","Executive Response Unit","P.O. Box 6500","Executive Response Unit","Sioux Falls","SD","57117"],
["Discover","Executive Customer Advocacy","P.O. Box 30943","Executive Customer Advocacy","Salt Lake City","UT","84130"],
["American Express","Executive Customer Relations","P.O. Box 981535","Executive Customer Relations","El Paso","TX","79998-1535"],
["Synchrony Bank","Executive Customer Relations","P.O. Box 965035","Executive Customer Relations","Orlando","FL","32896-5035"],
["Comenity Bank","Executive Customer Care","P.O. Box 182273","Executive Customer Care","Columbus","OH","43218"],
["Bread Financial","Executive Customer Relations","P.O. Box 182273","Executive Customer Relations","Columbus","OH","43218"],
["Wells Fargo","Executive Office","P.O. Box 10335","Executive Office","Des Moines","IA","50306"],
["U.S. Bank","Executive Customer Relations","P.O. Box 6352","Executive Customer Relations","Fargo","ND","58125"],
["PNC Bank","Executive Client Relations","P.O. Box 3429","Executive Client Relations","Pittsburgh","PA","15230"],
["Truist Bank","Executive Resolution Team","P.O. Box 85024","Executive Resolution Team","Richmond","VA","23285"],
["Navy Federal Credit Union","Office of Consumer Advocacy","P.O. Box 3000","Consumer Advocacy","Merrifield","VA","22119"],
["Ally Bank","Executive Customer Care","P.O. Box 951","Executive Customer Care","Horsham","PA","19044"],
["Barclays Bank Delaware","Executive Office","P.O. Box 8801","Executive Office","Wilmington","DE","19899"],
["TD Bank","Customer Advocacy","P.O. Box 9547","Customer Advocacy","Portland","ME","04112"],
["Fifth Third Bank","Executive Resolution Team","P.O. Box 630782","Executive Resolution Team","Cincinnati","OH","45263"],
["Regions Bank","Executive Customer Relations","P.O. Box 11007","Executive Customer Relations","Birmingham","AL","35288"],
["Huntington National Bank","Customer Advocacy","P.O. Box 1558","Customer Advocacy","Columbus","OH","43216"],
  ["Goldman Sachs Bank USA (Marcus)","Executive Office","P.O. Box 70379","Executive Customer Relations","Philadelphia","PA","19176-0379"],
["M&T Bank","Executive Customer Relations","P.O. Box 1288","Executive Customer Relations","Buffalo","NY","14240"],
["KeyBank","Executive Client Relations","127 Public Square","Executive Client Relations","Cleveland","OH","44114"],
["Citizens Bank","Executive Customer Advocacy","One Citizens Plaza","Executive Customer Advocacy","Providence","RI","02903"],
["First Citizens Bank","Executive Customer Relations","P.O. Box 27131","Executive Customer Relations","Raleigh","NC","27611"],
["BMO Bank N.A.","Executive Customer Relations","320 South Canal Street","Executive Customer Relations","Chicago","IL","60606"],
["First Horizon Bank","Executive Response Team","P.O. Box 84","Executive Response Team","Memphis","TN","38101"],
["Cadence Bank","Executive Customer Care","P.O. Box 1187","Executive Customer Care","Tupelo","MS","38802"],
["Associated Bank","Executive Customer Care","P.O. Box 13307","Executive Customer Care","Green Bay","WI","54307"],
["Webster Bank","Executive Customer Relations","P.O. Box 1986","Executive Customer Relations","Waterbury","CT","06722"],
["Valley National Bank","Executive Customer Relations","615 Main Avenue","Executive Customer Relations","Passaic","NJ","07055"],
["Old National Bank","Executive Customer Care","One Main Street","Executive Customer Care","Evansville","IN","47708"],
["Commerce Bank","Executive Customer Relations","P.O. Box 419248","Executive Customer Relations","Kansas City","MO","64141"],
["UMB Bank","Executive Customer Relations","P.O. Box 419226","Executive Customer Relations","Kansas City","MO","64141"],
["Frost Bank","Executive Customer Relations","P.O. Box 1600","Executive Customer Relations","San Antonio","TX","78296"],
["Arvest Bank","Executive Customer Relations","P.O. Box 799","Executive Customer Relations","Lowell","AR","72745"],
["Bank OZK","Executive Customer Relations","P.O. Box 196","Executive Customer Relations","Little Rock","AR","72203"],
["SouthState Bank","Executive Customer Care","P.O. Box 118068","Executive Customer Care","Charleston","SC","29423"],
["Atlantic Union Bank","Executive Customer Relations","P.O. Box 27032","Executive Customer Relations","Richmond","VA","23261"],
["Independent Financial","Executive Customer Relations","7777 Henneman Way","Executive Customer Relations","McKinney","TX","75070"],
["Texas Capital Bank","Executive Client Relations","2000 McKinney Avenue","Executive Client Relations","Dallas","TX","75201"],
["Simmons Bank","Executive Customer Relations","P.O. Box 7009","Executive Customer Relations","Pine Bluff","AR","71611"],
["FirstBank","Executive Customer Relations","12345 West Colfax Avenue","Executive Customer Relations","Lakewood","CO","80215"],
["Western Alliance Bank","Executive Customer Relations","One East Washington Street","Executive Customer Relations","Phoenix","AZ","85004"],
["Customers Bank","Executive Customer Advocacy","701 Reading Avenue","Executive Customer Advocacy","West Reading","PA","19611"],
["Axos Bank","Executive Customer Relations","P.O. Box 509127","Executive Customer Relations","San Diego","CA","92150"],
["SoFi Bank","Executive Customer Relations","2750 East Cottonwood Parkway","Executive Customer Relations","Cottonwood Heights","UT","84121"],
["FirstBank Puerto Rico","Executive Customer Relations","1519 Ponce de León Avenue","Executive Customer Relations","San Juan","PR","00908"],
["City National Bank","Executive Client Relations","555 South Flower Street","Executive Client Relations","Los Angeles","CA","90071"],
["Hancock Whitney Bank","Executive Customer Relations","P.O. Box 4019","Executive Customer Relations","Gulfport","MS","39502"],
  ["Capital One","General Counsel","1680 Capital One Drive","Legal Department","McLean","VA","22102"],
["JPMorgan Chase","General Counsel","383 Madison Avenue","Legal Department","New York","NY","10179"],
["Bank of America","General Counsel","100 North Tryon Street","Legal Department","Charlotte","NC","28255"],
["Wells Fargo","General Counsel","420 Montgomery Street","Legal Department","San Francisco","CA","94104"],
["Citibank","General Counsel","388 Greenwich Street","Legal Department","New York","NY","10013"],
["American Express","General Counsel","200 Vesey Street","Legal Department","New York","NY","10285"],
["Discover Bank","General Counsel","2500 Lake Cook Road","Legal Department","Riverwoods","IL","60015"],
["Synchrony Bank","General Counsel","777 Long Ridge Road","Legal Department","Stamford","CT","06902"],
["Comenity Bank","General Counsel","3095 Loyalty Circle","Legal Department","Columbus","OH","43219"],
["Barclays Bank Delaware","General Counsel","125 South West Street","Legal Department","Wilmington","DE","19801"],
["Goldman Sachs Bank USA","General Counsel","200 West Street","Legal Department","New York","NY","10282"],
["Morgan Stanley Bank","General Counsel","1585 Broadway","Legal Department","New York","NY","10036"],
["Ally Bank","General Counsel","500 Woodward Avenue","Legal Department","Detroit","MI","48226"],
["U.S. Bank","General Counsel","800 Nicollet Mall","Legal Department","Minneapolis","MN","55402"],
["PNC Bank","General Counsel","300 Fifth Avenue","Legal Department","Pittsburgh","PA","15222"],
["Truist Bank","General Counsel","214 North Tryon Street","Legal Department","Charlotte","NC","28202"],
["TD Bank","General Counsel","2035 Limestone Road","Legal Department","Wilmington","DE","19808"],
["Fifth Third Bank","General Counsel","38 Fountain Square Plaza","Legal Department","Cincinnati","OH","45263"],
["Regions Bank","General Counsel","1900 Fifth Avenue North","Legal Department","Birmingham","AL","35203"],
["Huntington National Bank","General Counsel","41 South High Street","Legal Department","Columbus","OH","43215"],
["M&T Bank","General Counsel","One M&T Plaza","Legal Department","Buffalo","NY","14203"],
["KeyBank","General Counsel","127 Public Square","Legal Department","Cleveland","OH","44114"],
["Citizens Bank","General Counsel","One Citizens Plaza","Legal Department","Providence","RI","02903"],
["First Citizens Bank","General Counsel","4300 Six Forks Road","Legal Department","Raleigh","NC","27609"],
["BMO Bank N.A.","General Counsel","320 South Canal Street","Legal Department","Chicago","IL","60606"],
["First Horizon Bank","General Counsel","165 Madison Avenue","Legal Department","Memphis","TN","38103"],
["Cadence Bank","General Counsel","201 South Spring Street","Legal Department","Tupelo","MS","38804"],
["Associated Bank","General Counsel","433 Main Street","Legal Department","Green Bay","WI","54301"],
["Webster Bank","General Counsel","200 Elm Street","Legal Department","Stamford","CT","06902"],
["Valley National Bank","General Counsel","615 Main Avenue","Legal Department","Passaic","NJ","07055"],
["Old National Bank","General Counsel","One Main Street","Legal Department","Evansville","IN","47708"],
["Commerce Bank","General Counsel","1000 Walnut Street","Legal Department","Kansas City","MO","64106"],
["UMB Bank","General Counsel","1010 Grand Boulevard","Legal Department","Kansas City","MO","64106"],
["Frost Bank","General Counsel","111 West Houston Street","Legal Department","San Antonio","TX","78205"],
["Arvest Bank","General Counsel","75 North East Street","Legal Department","Fayetteville","AR","72701"],
["Bank OZK","General Counsel","17901 Chenal Parkway","Legal Department","Little Rock","AR","72223"],
["SouthState Bank","General Counsel","520 Gervais Street","Legal Department","Columbia","SC","29201"],
["Atlantic Union Bank","General Counsel","1051 East Cary Street","Legal Department","Richmond","VA","23219"],
["Texas Capital Bank","General Counsel","2000 McKinney Avenue","Legal Department","Dallas","TX","75201"],
["Simmons Bank","General Counsel","501 Main Street","Legal Department","Pine Bluff","AR","71601"],
["Western Alliance Bank","General Counsel","One East Washington Street","Legal Department","Phoenix","AZ","85004"],
["Customers Bank","General Counsel","701 Reading Avenue","Legal Department","West Reading","PA","19611"],
["Axos Bank","General Counsel","4350 La Jolla Village Drive","Legal Department","San Diego","CA","92122"],
["SoFi Bank","General Counsel","2750 East Cottonwood Parkway","Legal Department","Cottonwood Heights","UT","84121"],
["City National Bank","General Counsel","555 South Flower Street","Legal Department","Los Angeles","CA","90071"],
["Hancock Whitney Bank","General Counsel","2510 14th Street","Legal Department","Gulfport","MS","39501"],
["Navy Federal Credit Union","General Counsel","820 Follin Lane","Legal Department","Vienna","VA","22180"],
["PenFed Credit Union","General Counsel","2930 Eisenhower Avenue","Legal Department","Alexandria","VA","22314"],
["BECU","General Counsel","12770 Gateway Drive","Legal Department","Tukwila","WA","98168"],
["SchoolsFirst Federal Credit Union","General Counsel","15442 Newport Avenue","Legal Department","Tustin","CA","92780"],
["Capital One","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["JPMorgan Chase","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Bank of America","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Wells Fargo","Registered Agent","CT Corporation System","1209 Orange Street","Wilmington","DE","19801"],
["Citibank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["American Express","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Discover Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Synchrony Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Comenity Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Barclays Bank Delaware","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Goldman Sachs Bank USA","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Morgan Stanley Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Ally Bank","Registered Agent","CT Corporation System","1209 Orange Street","Wilmington","DE","19801"],
["U.S. Bank","Registered Agent","CT Corporation System","1209 Orange Street","Wilmington","DE","19801"],
["PNC Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Truist Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["TD Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Fifth Third Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Regions Bank","Registered Agent","CT Corporation System","1209 Orange Street","Wilmington","DE","19801"],
["Huntington National Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["M&T Bank","Registered Agent","CT Corporation System","1209 Orange Street","Wilmington","DE","19801"],
["KeyBank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Citizens Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["First Citizens Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["BMO Bank N.A.","Registered Agent","CT Corporation System","1209 Orange Street","Wilmington","DE","19801"],
["First Horizon Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Cadence Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Associated Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Webster Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Valley National Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Old National Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Commerce Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["UMB Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Frost Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Arvest Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Bank OZK","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["SouthState Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Atlantic Union Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Texas Capital Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Simmons Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Western Alliance Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Customers Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Axos Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["SoFi Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["City National Bank","Registered Agent","CT Corporation System","1209 Orange Street","Wilmington","DE","19801"],
["Hancock Whitney Bank","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["Navy Federal Credit Union","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["PenFed Credit Union","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["BECU","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
["SchoolsFirst Federal Credit Union","Registered Agent","Corporation Service Company","251 Little Falls Drive","Wilmington","DE","19808"],
  ["Capital One","Office of the President","P.O. Box 30285","Executive Escalations","Salt Lake City","UT","84130-0285"],
["JPMorgan Chase","Executive Office","P.O. Box 15298","Executive Escalations","Wilmington","DE","19850-5298"],
["Bank of America","Office of the President","P.O. Box 25118","Executive Escalations","Tampa","FL","33622-5118"],
["Wells Fargo","Executive Office","P.O. Box 10335","Executive Escalations","Des Moines","IA","50306"],
["Citibank","Executive Response Unit","P.O. Box 6500","Executive Escalations","Sioux Falls","SD","57117"],
["American Express","Executive Customer Relations","P.O. Box 981535","Executive Escalations","El Paso","TX","79998-1535"],
["Discover Bank","Executive Customer Advocacy","P.O. Box 30943","Executive Escalations","Salt Lake City","UT","84130"],
["Synchrony Bank","Executive Customer Relations","P.O. Box 965035","Executive Escalations","Orlando","FL","32896-5035"],
["Comenity Bank","Executive Customer Care","P.O. Box 182273","Executive Escalations","Columbus","OH","43218"],
["Barclays Bank Delaware","Executive Office","P.O. Box 8801","Executive Escalations","Wilmington","DE","19899"],
["Goldman Sachs Bank USA","Executive Office","P.O. Box 70379","Executive Escalations","Philadelphia","PA","19176-0379"],
["Morgan Stanley Bank","Executive Office","1585 Broadway","Executive Escalations","New York","NY","10036"],
["Ally Bank","Executive Customer Care","P.O. Box 951","Executive Escalations","Horsham","PA","19044"],
["U.S. Bank","Executive Customer Relations","P.O. Box 6352","Executive Escalations","Fargo","ND","58125"],
["PNC Bank","Executive Client Relations","P.O. Box 3429","Executive Escalations","Pittsburgh","PA","15230"],
["Truist Bank","Executive Resolution Team","P.O. Box 85024","Executive Escalations","Richmond","VA","23285"],
["TD Bank","Customer Advocacy","P.O. Box 9547","Executive Escalations","Portland","ME","04112"],
["Fifth Third Bank","Executive Resolution Team","P.O. Box 630782","Executive Escalations","Cincinnati","OH","45263"],
["Regions Bank","Executive Customer Relations","P.O. Box 11007","Executive Escalations","Birmingham","AL","35288"],
["Huntington National Bank","Customer Advocacy","P.O. Box 1558","Executive Escalations","Columbus","OH","43216"],
["M&T Bank","Executive Customer Relations","P.O. Box 1288","Executive Escalations","Buffalo","NY","14240"],
["KeyBank","Executive Client Relations","127 Public Square","Executive Escalations","Cleveland","OH","44114"],
["Citizens Bank","Executive Customer Advocacy","One Citizens Plaza","Executive Escalations","Providence","RI","02903"],
["First Citizens Bank","Executive Customer Relations","P.O. Box 27131","Executive Escalations","Raleigh","NC","27611"],
["BMO Bank N.A.","Executive Customer Relations","320 South Canal Street","Executive Escalations","Chicago","IL","60606"],
["First Horizon Bank","Executive Response Team","P.O. Box 84","Executive Escalations","Memphis","TN","38101"],
["Cadence Bank","Executive Customer Care","P.O. Box 1187","Executive Escalations","Tupelo","MS","38802"],
["Associated Bank","Executive Customer Care","P.O. Box 13307","Executive Escalations","Green Bay","WI","54307"],
["Webster Bank","Executive Customer Relations","P.O. Box 1986","Executive Escalations","Waterbury","CT","06722"],
["Valley National Bank","Executive Customer Relations","615 Main Avenue","Executive Escalations","Passaic","NJ","07055"],
["Old National Bank","Executive Customer Care","One Main Street","Executive Escalations","Evansville","IN","47708"],
["Commerce Bank","Executive Customer Relations","P.O. Box 419248","Executive Escalations","Kansas City","MO","64141"],
["UMB Bank","Executive Customer Relations","P.O. Box 419226","Executive Escalations","Kansas City","MO","64141"],
["Frost Bank","Executive Customer Relations","P.O. Box 1600","Executive Escalations","San Antonio","TX","78296"],
["Arvest Bank","Executive Customer Relations","P.O. Box 799","Executive Escalations","Lowell","AR","72745"],
["Bank OZK","Executive Customer Relations","P.O. Box 196","Executive Escalations","Little Rock","AR","72203"],
["SouthState Bank","Executive Customer Care","P.O. Box 118068","Executive Escalations","Charleston","SC","29423"],
["Atlantic Union Bank","Executive Customer Relations","P.O. Box 27032","Executive Escalations","Richmond","VA","23261"],
["Texas Capital Bank","Executive Client Relations","2000 McKinney Avenue","Executive Escalations","Dallas","TX","75201"],
["Simmons Bank","Executive Customer Relations","P.O. Box 7009","Executive Escalations","Pine Bluff","AR","71611"],
["Western Alliance Bank","Executive Customer Relations","One East Washington Street","Executive Escalations","Phoenix","AZ","85004"],
["Customers Bank","Executive Customer Advocacy","701 Reading Avenue","Executive Escalations","West Reading","PA","19611"],
["Axos Bank","Executive Customer Relations","P.O. Box 509127","Executive Escalations","San Diego","CA","92150"],
["SoFi Bank","Executive Customer Relations","2750 East Cottonwood Parkway","Executive Escalations","Cottonwood Heights","UT","84121"],
["City National Bank","Executive Client Relations","555 South Flower Street","Executive Escalations","Los Angeles","CA","90071"],
["Hancock Whitney Bank","Executive Customer Relations","P.O. Box 4019","Executive Escalations","Gulfport","MS","39502"],
["Navy Federal Credit Union","Office of Consumer Advocacy","P.O. Box 3000","Executive Escalations","Merrifield","VA","22119"],
["PenFed Credit Union","Executive Customer Relations","P.O. Box 1432","Executive Escalations","Alexandria","VA","22313"],
["BECU","Member Advocacy","P.O. Box 97050","Executive Escalations","Seattle","WA","98124"],
["SchoolsFirst Federal Credit Union","Executive Member Care","P.O. Box 11547","Executive Escalations","Santa Ana","CA","92711"]
 
].map((row, index) => ({
  id: `bureau-${index + 1}`,
  bureau: row[0] as BureauAddress["bureau"],
  department: row[1],
  addressLine1: row[2],
  addressLine2: row[3] || undefined,
  city: row[4],
  state: row[5],
  zip: row[6],
  isActive: true,
}));

export const starterTemplates: LetterTemplate[] = [
  {
    id: "template-initial-dispute",
    templateName: "Initial Bureau Dispute",
    category: "Miscellaneous",
    description:
      "First-round request to investigate inaccurate or unverifiable credit information.",
    isActive: true,
    createdAt: seededAt,
    updatedAt: seededAt,
    body: `<p>{{CLIENT_NAME}}<br>{{CLIENT_ADDRESS}}<br>{{CLIENT_CITY}}, {{CLIENT_STATE}} {{CLIENT_ZIP}}</p><p>{{CURRENT_DATE}}</p><p>{{BUREAU_NAME}}<br>{{BUREAU_DEPARTMENT}}<br>{{BUREAU_ADDRESS}}</p><p><strong>Re: Request for investigation of inaccurate credit information</strong></p><p>To Whom It May Concern:</p><p>I am writing to dispute inaccurate information appearing in my consumer credit file. After carefully reviewing my report, I identified information that I believe is incomplete, inaccurate, or cannot be verified.</p><p>Please conduct a reasonable reinvestigation of the disputed information in accordance with the Fair Credit Reporting Act. Please provide the method of verification used and send me an updated copy of my credit report after your investigation is complete.</p><p>The disputed items and supporting documentation are included with this letter.</p><p>Sincerely,</p><p>{{CLIENT_NAME}}</p>`,
  },
  {
    id: "template-identity-theft",
    templateName: "Identity Theft Block Request",
    category: "Fraud",
    description:
      "Requests a block of information caused by identity theft with supporting documents.",
    isActive: true,
    createdAt: seededAt,
    updatedAt: seededAt,
    body: `<p>{{CLIENT_NAME}}<br>{{CLIENT_ADDRESS}}<br>{{CLIENT_CITY}}, {{CLIENT_STATE}} {{CLIENT_ZIP}}</p><p>{{CURRENT_DATE}}</p><p>{{BUREAU_NAME}}<br>{{BUREAU_DEPARTMENT}}<br>{{BUREAU_ADDRESS}}</p><p><strong>Re: Identity theft information block request</strong></p><p>To Whom It May Concern:</p><p>I am a victim of identity theft. The items identified in my enclosed documentation do not relate to any transaction that I made or authorized.</p><p>Please block the reporting of this information, notify the relevant furnishers, and send written confirmation of the action taken. I have enclosed proof of identity, an identity theft report, and a copy of my credit report identifying the affected items.</p><p>Sincerely,</p><p>{{CLIENT_NAME}}<br>{{CLIENT_PHONE}}<br>{{CLIENT_EMAIL}}</p>`,
  },
  {
    id: "template-method-verification",
    templateName: "Method of Verification Follow-Up",
    category: "Miscellaneous",
    description:
      "Requests the procedure used to determine the accuracy of a disputed item.",
    isActive: true,
    createdAt: seededAt,
    updatedAt: seededAt,
    body: `<p>{{CLIENT_NAME}}<br>{{CLIENT_ADDRESS}}<br>{{CLIENT_CITY}}, {{CLIENT_STATE}} {{CLIENT_ZIP}}</p><p>{{CURRENT_DATE}}</p><p>{{BUREAU_NAME}}<br>{{BUREAU_DEPARTMENT}}<br>{{BUREAU_ADDRESS}}</p><p><strong>Re: Request for description of reinvestigation procedure</strong></p><p>To Whom It May Concern:</p><p>I recently received the results of your reinvestigation. I am requesting a description of the procedure used to determine the accuracy and completeness of the disputed information, including the business name, address, and telephone number of each furnisher contacted.</p><p>Please provide this information within the time allowed by applicable law.</p><p>Sincerely,</p><p>{{CLIENT_NAME}}</p>`,
  },
  {
    id: "template-intent-sue",
    templateName: "Intent to Sue Notice",
    category: "Miscellaneous",
    description: "Formal notice template reserved for administrator review.",
    isActive: false,
    createdAt: seededAt,
    updatedAt: seededAt,
    body: `<p>{{CLIENT_NAME}}<br>{{CLIENT_ADDRESS}}<br>{{CLIENT_CITY}}, {{CLIENT_STATE}} {{CLIENT_ZIP}}</p><p>{{CURRENT_DATE}}</p><p>{{BUREAU_NAME}}<br>{{BUREAU_ADDRESS}}</p><p><strong>Re: Notice of unresolved dispute</strong></p><p>To Whom It May Concern:</p><p>This letter concerns inaccurate information that remains unresolved following prior disputes. Please review the enclosed record and provide a complete written response.</p><p>Sincerely,</p><p>{{CLIENT_NAME}}</p>`,
  },
];

export const templateCategories = [
  "Collection",
  "Charge-Off Account",
  "Inquiry",
  "Personal Information",
  "Bankruptcy",
  "Late Payments",
  "Fraud",
  "Consumer Reporting Agencies",
  "Check Systems and Early Warnings",
  "Compliance Officers",
  "Risk Officers and Registered Agents",
  "Miscellaneous",
] as const;
