import type {
  LibraryCategory,
  LibraryResource,
} from "./libraryTypes";

export const libraryCategoryDescriptions: Record<LibraryCategory, string> = {
  "Legal Documents": "Notices, affidavits, reference forms, and legal resources.",
  Collections: "Collection account education, workflows, and templates.",
  "Charge-Off": "Resources for understanding and disputing charge-off reporting.",
  Inquiries: "Guides and templates for credit inquiry concerns.",
  "Personal Information": "Name, address, employment, and identity data resources.",
  Education: "Foundational credit education and Academy study materials.",
  "Credit Building": "Action plans, trackers, and responsible credit-building guides.",
  Bankruptcy: "Bankruptcy reporting education, references, and templates.",
  "Payment History": "Late-payment, delinquency, and payment-history resources.",
  "Metro 2": "Metro 2 reporting standards, field references, and study tools.",
  Miscellaneous: "Additional downloads and specialty resources.",
};

const now = new Date().toISOString();

export const libraryPreviewResources: LibraryResource[] = [
  {
    id: "preview-credit-foundations",
    title: "Credit Repair Foundations",
    description:
      "A student-friendly guide to credit reports, dispute preparation, documentation, and responsible follow-through.",
    category: "Education",
    resourceType: "E-book",
    tags: ["credit basics", "education", "getting started"],
    fileName: "credit-repair-foundations.pdf",
    fileSize: 2_450_000,
    mimeType: "application/pdf",
    externalUrl: "#",
    isFeatured: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "preview-collection-checklist",
    title: "Collection Account Review Checklist",
    description:
      "A practical checklist students can use before preparing a collection account dispute.",
    category: "Collections",
    resourceType: "Checklist",
    tags: ["collections", "review", "checklist"],
    fileName: "collection-review-checklist.pdf",
    fileSize: 680_000,
    mimeType: "application/pdf",
    externalUrl: "#",
    isFeatured: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "preview-metro2-reference",
    title: "Metro 2 Quick Reference",
    description:
      "A concise learning reference for common Metro 2 terms, fields, and reporting concepts.",
    category: "Metro 2",
    resourceType: "Reference",
    tags: ["metro 2", "reporting", "reference"],
    fileName: "metro-2-quick-reference.pdf",
    fileSize: 1_120_000,
    mimeType: "application/pdf",
    externalUrl: "#",
    isFeatured: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "preview-inquiry-template",
    title: "Inquiry Documentation Worksheet",
    description:
      "An organized worksheet for recording inquiry details and supporting documentation.",
    category: "Inquiries",
    resourceType: "Worksheet",
    tags: ["inquiries", "documentation", "worksheet"],
    fileName: "inquiry-documentation-worksheet.pdf",
    fileSize: 540_000,
    mimeType: "application/pdf",
    externalUrl: "#",
    isFeatured: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "preview-building-plan",
    title: "90-Day Credit Building Plan",
    description:
      "A clear 90-day learning and action plan for building stronger credit habits.",
    category: "Credit Building",
    resourceType: "Guide",
    tags: ["credit building", "action plan", "habits"],
    fileName: "90-day-credit-building-plan.pdf",
    fileSize: 890_000,
    mimeType: "application/pdf",
    externalUrl: "#",
    isFeatured: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "preview-personal-info",
    title: "Personal Information Audit",
    description:
      "A printable audit for reviewing names, addresses, employers, and other personal data.",
    category: "Personal Information",
    resourceType: "Worksheet",
    tags: ["personal information", "audit", "credit report"],
    fileName: "personal-information-audit.pdf",
    fileSize: 610_000,
    mimeType: "application/pdf",
    externalUrl: "#",
    isFeatured: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];
